services:
  java-maven-service:
    container_name: calculator
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - PORT=8080
